# Generated by Django 3.2.8 on 2022-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0004_product_specail_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
